class Appsecrets{
  static const String superSecretURL = "https://axqzdjwhqzmnoghearof.supabase.co";
  static const String supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4cXpkandocXptbm9naGVhcm9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjAwMzc2MDMsImV4cCI6MjAzNTYxMzYwM30.fPVdXKuJqDHaWNpIjPf66x1KFRLch88YKrmR11YYX78";
}